package Main;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.sql.SQLException;

/**
 *
 * @author UFT
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        URL url = this.getClass().getResource("bola.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo); 
       
        this.setLocationRelativeTo(null);
        ActionListener equipe1 = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String e1 = (String) Equipe1_ComboBox.getSelectedItem();
                Equipe1_TextField.setText(e1);
            }
        };
        
        Equipe1_ComboBox.addActionListener(equipe1);
        
        ActionListener equipe2 = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String e2 = (String) Equipe2_ComboBox.getSelectedItem();
                Equipe2_TextField.setText(e2);
            }
        };
        
        Equipe2_ComboBox.addActionListener(equipe2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Equipe1_ComboBox = new javax.swing.JComboBox<>();
        Equipe1_TextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Equipe2_ComboBox = new javax.swing.JComboBox<>();
        Equipe2_TextField = new javax.swing.JTextField();
        Ok_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rumo ao HEXA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Primeira equipe"));

        Equipe1_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Russia", "Brazil", "Iran", "Japan", "Mexico", "Belgium", "Korea Republic", "Saudi Arabia", "Germany", "England", "Spain", "Nigeria", "Costa Rica", "Poland", "Egypt", "Iceland", "Serbia", "France", "Portugal", "Argentina", "Colombia", "Uruguay", "Panama", "Senegal", "Morocco", "Tunisia", "Switzerland", "Croatia", "Sweden", "Denmark", "Australia", "Peru" }));

        Equipe1_TextField.setText("Russia");
        Equipe1_TextField.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Equipe1_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Equipe1_TextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Equipe1_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Equipe1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Segunda equipe"));

        Equipe2_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Russia", "Brazil", "Iran", "Japan", "Mexico", "Belgium", "Korea Republic", "Saudi Arabia", "Germany", "England", "Spain", "Nigeria", "Costa Rica", "Poland", "Egypt", "Iceland", "Serbia", "France", "Portugal", "Argentina", "Colombia", "Uruguay", "Panama", "Senegal", "Morocco", "Tunisia", "Switzerland", "Croatia", "Sweden", "Denmark", "Australia", "Peru" }));

        Equipe2_TextField.setText("Russia");
        Equipe2_TextField.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Equipe2_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Equipe2_TextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Equipe2_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Equipe2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        Ok_button.setText("OK");
        Ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ok_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(Ok_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(Ok_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ok_buttonActionPerformed
        //Aqui é todo o código que será feito para prever os resultados
        
        String equipe1 = Equipe1_TextField.getText();
        String equipe2 = Equipe2_TextField.getText();

        Controller c = new Controller();
        try {
            c.LerBanco(equipe1, equipe2);
        } catch (SQLException ex) {
            System.err.println("ERRO:. "+ex);
        }
            
//        String equipe1 = Equipe1_TextField.getText();
//        String equipe2 = Equipe2_TextField.getText();
//        System.out.println(equipe1);
//        System.out.println(equipe2);
//        
//        if(equipe1.equals(equipe2)){
//            JOptionPane.showMessageDialog(null, "Não escolha 2 seleções iguais seu doente mental", "Alerta", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//        
//        try (Connection con = new ConnectionFactory().getConnection()) {
//            PreparedStatement stmt = con.prepareStatement("select * from equipes.jogadores");
//            ResultSet rs = stmt.executeQuery();
//            
//            int time1 = 0;
//            int time2 = 0;
//            int count1 = 0;
//            int count2 = 0;
//            int ranking1 = 0;
//            int ranking2 = 0;
//
//            
//            while (rs.next()) {
//                String aux = rs.getString("selecao");
////                System.out.println("------------------------------");
////                System.out.println("Jogador:. "+rs.getString("nome"));
////                System.out.println("Selecao:. "+rs.getString("selecao"));
////                System.out.println("Overall:. "+rs.getInt("overall"));
////                System.out.println("Posição:. "+rs.getString("posicao"));
//                
//                if(equipe1.equals(aux)){
//                    count1++;
//                    time1 += rs.getInt("overall");
//                    ranking1 = rs.getInt("ranking_fifa");
//                }
//                if(equipe2.equals(aux)){
//                    count2++;
//                    time2 += rs.getInt("overall");
//                    ranking2 = rs.getInt("ranking_fifa");
//                }
//            }
//            
//            float media_1 = 0;
//            float media_2 = 0;
//            
//            try{media_1 = (float)time1/count1;}catch(Exception e){System.out.println(e);}
//            try{media_2 = (float)time2/count2;}catch(Exception e){System.out.println(e);}
//            
//            float total_1 = (float) ((media_1 * 0.5) + ((100 - ranking1) * 0.5));
//            float total_2 = (float) ((media_2 * 0.5) + ((100 - ranking2) * 0.5));
//
//            
//            /*
//            if(media_1 >= media_2){
//                JOptionPane.showMessageDialog(null, equipe1+" vence!");
//                System.out.println(equipe1+ " vence!");
//            }
//            else{
//                JOptionPane.showMessageDialog(null, equipe2+" vence!");
//                System.out.println(equipe2+ " vence!");
//            }
//            */
//            System.out.println("total1:. "+total_1);
//            System.out.println("total2:. "+total_2);
//            
//            if(total_1 >= total_2){
//                JOptionPane.showMessageDialog(null, equipe1+" vence!");    
//                System.out.println(equipe1+ " vence!");
//            }
//            else{
//                JOptionPane.showMessageDialog(null, equipe2+" vence!");
//                System.out.println(equipe2+ " vence!");
//            }
//            
//            System.out.println("Media "+equipe1+":. "+media_1);
//            System.out.println("Media "+equipe2+":. "+media_2);
//
//            
//            rs.close();
//            stmt.close();
//        } catch (SQLException ex) {
//            System.out.println("ERRO!"+ ex);
//        }
        
        
        
    }//GEN-LAST:event_Ok_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Equipe1_ComboBox;
    private javax.swing.JTextField Equipe1_TextField;
    private javax.swing.JComboBox<String> Equipe2_ComboBox;
    private javax.swing.JTextField Equipe2_TextField;
    private javax.swing.JButton Ok_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
